version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sla_monitoring
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sla_monitoring"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/sla_monitoring
    ports:
      - '8000:8000'
      - '8501:8501'  # Streamlit UI

volumes:
  db_data: